import KrushJson from '@/rolemaster/combatdata/CritTable/Krush.json';
import PunctureJson from '@/rolemaster/combatdata/CritTable/Puncture.json';
import SlashJson from '@/rolemaster/combatdata/CritTable/Slash.json';
import StrikesJson from '@/rolemaster/combatdata/CritTable/Strikes.json';
import SweepsJson from '@/rolemaster/combatdata/CritTable/Sweeps.json';
import UnbalanceJson from '@/rolemaster/combatdata/CritTable/Unbalance.json';
import ImpactJson from '@/rolemaster/combatdata/CritTable/Impact.json';
import GrappleJson from '@/rolemaster/combatdata/CritTable/Grapple.json';
import HeatJson from '@/rolemaster/combatdata/CritTable/Heat.json';
import ColdJson from '@/rolemaster/combatdata/CritTable/Cold.json';
import ElectricityJson from '@/rolemaster/combatdata/CritTable/Electricity.json';
import HolyJson from '@/rolemaster/combatdata/CritTable/Holy.json';
import StreamJson from '@/rolemaster/combatdata/CritTable/Stream.json';
import AcidJson from '@/rolemaster/combatdata/CritTable/Acid.json';
import SubdualJson from '@/rolemaster/combatdata/CritTable/Subdual.json';


const critTables = {
  Krush: KrushJson,
  Puncture: PunctureJson,
  Slash: SlashJson,
  Strikes: StrikesJson,
  Sweeps: SweepsJson,
  Unbalance: UnbalanceJson,
  Impact: ImpactJson,
  Grapple: GrappleJson,
  Heat: HeatJson,
  Cold: ColdJson,
  Electricity: ElectricityJson,
  Holy: HolyJson,
  Stream: StreamJson,
  Acid: AcidJson,
  Subdual: SubdualJson,
};

const critKeyMapping = {
  H: critTables.Heat,
  O: critTables.Cold,
  L: critTables.Electricity,
  I: critTables.Impact,
  K: critTables.Krush,
  P: critTables.Puncture,
  S: critTables.Slash,
  T: critTables.Strikes,
  U: critTables.Unbalance,
  W: critTables.Sweeps,
  G: critTables.Grapple,
};

const critOptions = [
  { value: 'Krush', label: '鈍擊' },
  { value: 'Puncture', label: '穿刺' },
  { value: 'Slash', label: '揮砍' },
  { value: 'Strikes', label: '打擊' },
  { value: 'Sweeps', label: '橫掃&摔投' },
  { value: 'Unbalance', label: '不平衡' },
  { value: 'Impact', label: '衝擊' },
  { value: 'Grapple', label: '擒拿' },
  { value: 'Heat', label: '熱量' },
  { value: 'Cold', label: '寒冷' },
  { value: 'Electricity', label: '閃電' },
  { value: 'Holy', label: '神聖' },
  { value: 'Stream', label: '蒸氣' },
  { value: 'Acid', label: '強酸' },
  { value: 'Subdual', label: '制伏' },
];

const critSeverityOptions = [
  { value: 'Z', label: 'Z' },
  { value: 'A', label: 'A' },
  { value: 'B', label: 'B' },
  { value: 'C', label: 'C' },
  { value: 'D', label: 'D' },
  { value: 'E', label: 'E' },
  { value: 'F', label: 'E+A' },
  { value: 'G', label: 'E+B' },
  { value: 'H', label: 'E+C' },
  { value: 'I', label: 'E+C+A' },
  { value: 'J', label: 'E+C+B' }
];

const hitLocationMapping = {
  1: '頭部',
  2: '胸部',
  3: '胸部',
  4: '腹部',
  5: '腹部',
  6: '腿部',
  7: '腿部',
  8: '腿部',
  9: '腿部',
  10: '腿部',
  11: '手臂',
  12: '手臂',
  13: '手臂',
  14: '手臂',
  15: '手臂',
  16: '頭部',
  17: '頭部',
  18: '頭部',
  19: '頭部',
  20: '頭部',
  21: '胸部',
  22: '胸部',
  23: '胸部',
  24: '胸部',
  25: '胸部',
  26: '腹部',
  27: '腹部',
  28: '腹部',
  29: '腹部',
  30: '腹部',
  31: '腹部',
  32: '腹部',
  33: '腹部',
  34: '腹部',
  35: '腹部',
  36: '腿部',
  37: '腿部',
  38: '腿部',
  39: '腿部',
  40: '腿部',
  41: '腿部',
  42: '腿部',
  43: '腿部',
  44: '腿部',
  45: '腿部',
  46: '手臂',
  47: '手臂',
  48: '手臂',
  49: '手臂',
  50: '手臂',
  51: '手臂',
  52: '手臂',
  53: '手臂',
  54: '手臂',
  55: '手臂',
  56: '手臂',
  57: '手臂',
  58: '手臂',
  59: '手臂',
  60: '手臂',
  61: '手臂',
  62: '手臂',
  63: '手臂',
  64: '手臂',
  65: '手臂',
  66: '腹部',
  67: '腿部',
  68: '腿部',
  69: '腿部',
  70: '腿部',
  71: '腿部',
  72: '腿部',
  73: '腿部',
  74: '腿部',
  75: '腿部',
  76: '胸部',
  77: '胸部',
  78: '胸部',
  79: '胸部',
  80: '胸部',
  81: '頭部',
  82: '頭部',
  83: '頭部',
  84: '頭部',
  85: '頭部',
  86: '手臂',
  87: '手臂',
  88: '手臂',
  89: '手臂',
  90: '手臂',
  91: '腿部',
  92: '腿部',
  93: '腿部',
  94: '腿部',
  95: '腿部',
  96: '腹部',
  97: '腹部',
  98: '胸部',
  99: '胸部',
  100: '頭部'
};


export { critTables, critKeyMapping , critOptions, critSeverityOptions, hitLocationMapping };